# Generated by Django 5.1.15 on 2026-05-22 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PipelineRun',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('task', models.CharField(choices=[('swing_scan', 'Swing scan'), ('screener_session', 'Screener session'), ('eod_enrichment', 'EOD enrichment')], db_index=True, max_length=32)),
                ('status', models.CharField(choices=[('running', 'Running'), ('success', 'Success'), ('failed', 'Failed')], default='running', max_length=12)),
                ('trigger', models.CharField(choices=[('beat', 'Beat'), ('manual', 'Manual')], default='beat', max_length=12)),
                ('started_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('summary', models.JSONField(blank=True, default=dict, help_text='Task result payload (counts, stats).')),
                ('error', models.TextField(blank=True, default='')),
            ],
            options={
                'ordering': ['-started_at'],
                'indexes': [models.Index(fields=['task', '-started_at'], name='system_pipe_task_9c869a_idx')],
            },
        ),
    ]
