# Generated by Django 5.1.15 on 2026-05-19 09:50

import apps.notifications.models
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents_core', '0001_initial'),
        ('notifications', '0001_initial'),
        ('strategies', '0002_signal_watchlistentry'),
        ('tenants', '0001_initial'),
        ('trading', '0002_trades'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TradingViewLink',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('display_name', models.CharField(blank=True, default='', help_text="Operator-facing label, e.g. 'Strategy: VWAP breakout'.", max_length=80)),
                ('webhook_secret', models.CharField(default=apps.notifications.models._make_webhook_secret, help_text='URL-path secret. Anyone with this can POST signals to this link.', max_length=64, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('autofire_enabled', models.BooleanField(default=False, help_text='When true, qualifying alerts spawn an AgentRun (still goes through RiskGuard).')),
                ('default_strategy_name', models.CharField(blank=True, default='', help_text="Strategy from the catalog to fire (e.g. 'directional'). Required when autofire is on.", max_length=64)),
                ('allowed_actions', models.JSONField(blank=True, default=list, help_text="If non-empty, only alerts whose `action` is in this list auto-fire. E.g. ['BUY','SELL'].")),
                ('last_received_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('receive_count', models.PositiveIntegerField(default=0)),
                ('last_error', models.CharField(blank=True, default='', max_length=512)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tradingview_links', to=settings.AUTH_USER_MODEL)),
                ('portfolio', models.ForeignKey(blank=True, help_text='Which portfolio the auto-fired run targets.', null=True, on_delete=django.db.models.deletion.PROTECT, to='trading.portfolio')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='tenants.tenant')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TradingViewSignal',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('received_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('raw_payload', models.TextField(help_text='Verbatim request body — TradingView lets users template anything.')),
                ('parsed', models.JSONField(blank=True, default=dict, help_text='{symbol, action, price, strategy, comment, ...} after parsing.')),
                ('parse_error', models.TextField(blank=True, default='')),
                ('link', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_signals', to='notifications.tradingviewlink')),
                ('signal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='strategies.signal')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='tenants.tenant')),
                ('workflow_run', models.ForeignKey(blank=True, help_text='Set when autofire was enabled and the run was queued.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='agents_core.agentrun')),
            ],
            options={
                'ordering': ['-received_at'],
            },
        ),
        migrations.AddIndex(
            model_name='tradingviewlink',
            index=models.Index(fields=['tenant', 'owner', '-created_at'], name='notificatio_tenant__7b7793_idx'),
        ),
        migrations.AddIndex(
            model_name='tradingviewlink',
            index=models.Index(fields=['webhook_secret'], name='notificatio_webhook_e8a5c7_idx'),
        ),
        migrations.AddIndex(
            model_name='tradingviewsignal',
            index=models.Index(fields=['tenant', '-received_at'], name='notificatio_tenant__ae340d_idx'),
        ),
        migrations.AddIndex(
            model_name='tradingviewsignal',
            index=models.Index(fields=['link', '-received_at'], name='notificatio_link_id_28a031_idx'),
        ),
    ]
