# Generated by Django 5.1.15 on 2026-05-19 14:39

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_tradingviewlink_tradingviewsignal_and_more'),
        ('tenants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TradingViewWatchlist',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=80)),
                ('description', models.TextField(blank=True, default='')),
                ('symbols', models.JSONField(blank=True, default=list, help_text='Uppercase symbols. Server normalises on save.')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tradingview_watchlists', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='tenants.tenant')),
            ],
            options={
                'ordering': ['-updated_at'],
                'indexes': [models.Index(fields=['tenant', 'owner', '-updated_at'], name='notificatio_tenant__f1e26e_idx')],
                'constraints': [models.UniqueConstraint(fields=('tenant', 'owner', 'name'), name='uniq_watchlist_name_per_owner')],
            },
        ),
    ]
