# Generated by Django 5.1.15 on 2026-05-19 14:54

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0003_tradingviewwatchlist'),
        ('tenants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='tradingviewwatchlist',
            name='config',
            field=models.JSONField(blank=True, default=dict, help_text='Kind-specific knobs (window_days, top_n, source, …). Empty for MANUAL.'),
        ),
        migrations.AddField(
            model_name='tradingviewwatchlist',
            name='kind',
            field=models.CharField(choices=[('MANUAL', 'Manual'), ('SIGNAL_RANK', 'Top-N by signal count'), ('SOURCE_HOT', 'Top-N for one source'), ('RECENT_ACTIVE', 'Any signal in last N hours'), ('TRADED_RECENTLY', 'Recently traded'), ('SHORTLIST_TODAY', "Today's premarket shortlist")], db_index=True, default='MANUAL', max_length=24),
        ),
        migrations.AddField(
            model_name='tradingviewwatchlist',
            name='symbols_refreshed_at',
            field=models.DateTimeField(blank=True, db_index=True, help_text='Last time an auto-resolver wrote `symbols`. Null for MANUAL.', null=True),
        ),
        migrations.AlterField(
            model_name='tradingviewwatchlist',
            name='symbols',
            field=models.JSONField(blank=True, default=list, help_text='Uppercase symbols. For MANUAL kind: source of truth — operator edits. For auto kinds: cached resolver output, refreshed by the watchlists.refresh task.'),
        ),
        migrations.AddIndex(
            model_name='tradingviewwatchlist',
            index=models.Index(fields=['kind', '-symbols_refreshed_at'], name='notificatio_kind_6e2840_idx'),
        ),
    ]
