# Generated by Django 5.1.15 on 2026-05-19 15:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0004_tradingviewwatchlist_config_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tradingviewlink',
            name='watchlist',
            field=models.ForeignKey(blank=True, help_text="Optional symbol-allowlist gate for autofire. When set, only alerts whose symbol appears in the watchlist's resolved set spawn an AgentRun (orthogonal to allowed_actions which gates the BUY/SELL side). Persistence + Signal-ledger writes still happen — only autofire is gated.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bound_links', to='notifications.tradingviewwatchlist'),
        ),
    ]
