# Generated by Django 5.1.15 on 2026-05-19 15:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0006_rename_watchlist'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='watchlist',
            new_name='notificatio_tenant__c536c5_idx',
            old_name='notificatio_tenant__f1e26e_idx',
        ),
        migrations.RenameIndex(
            model_name='watchlist',
            new_name='notificatio_kind_6040b6_idx',
            old_name='notificatio_kind_6e2840_idx',
        ),
        migrations.AlterField(
            model_name='watchlist',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='watchlists', to=settings.AUTH_USER_MODEL),
        ),
    ]
