# Generated by Django 5.1.15 on 2026-04-18 12:33

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        # BrokerLink absorbed from the old `broker` app in Phase 4b.
        ('tenants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BrokerLink',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('broker_name', models.CharField(max_length=32)),
                ('credential_arn', models.CharField(help_text='AWS Secrets Manager ARN', max_length=256)),
                ('status', models.CharField(choices=[('active', 'Active'), ('expired', 'Expired'), ('disabled', 'Disabled')], default='active', max_length=16)),
                ('last_refreshed_at', models.DateTimeField(blank=True, null=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='tenants.tenant')),
            ],
            options={
                'db_table': 'broker_brokerlink',
                'indexes': [models.Index(fields=['tenant', 'owner'], name='broker_brok_tenant__426f96_idx')],
            },
        ),
        migrations.CreateModel(
            name='Symbol',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('exchange', models.CharField(max_length=8)),
                ('token', models.CharField(max_length=32)),
                ('tradingsymbol', models.CharField(max_length=80)),
                ('name', models.CharField(blank=True, max_length=200)),
                ('segment', models.CharField(blank=True, max_length=16)),
                ('lot_size', models.IntegerField(default=1)),
                ('tick_size', models.DecimalField(decimal_places=4, default=0.05, max_digits=8)),
            ],
            options={
                'indexes': [models.Index(fields=['exchange', 'tradingsymbol'], name='market_data_exchang_7da0b8_idx')],
                'unique_together': {('exchange', 'token')},
            },
        ),
        migrations.CreateModel(
            name='Candle',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('interval', models.CharField(max_length=8)),
                ('t', models.DateTimeField(db_index=True)),
                ('o', models.DecimalField(decimal_places=4, max_digits=14)),
                ('h', models.DecimalField(decimal_places=4, max_digits=14)),
                ('l', models.DecimalField(decimal_places=4, max_digits=14)),
                ('c', models.DecimalField(decimal_places=4, max_digits=14)),
                ('v', models.BigIntegerField()),
                ('symbol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candles', to='market_data.symbol')),
            ],
            options={
                'indexes': [models.Index(fields=['symbol', 'interval', '-t'], name='market_data_symbol__260a9e_idx')],
                'unique_together': {('symbol', 'interval', 't')},
            },
        ),
    ]
