# Generated by Django 5.1.15 on 2026-04-18 12:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Symbol',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('exchange', models.CharField(max_length=8)),
                ('token', models.CharField(max_length=32)),
                ('tradingsymbol', models.CharField(max_length=80)),
                ('name', models.CharField(blank=True, max_length=200)),
                ('segment', models.CharField(blank=True, max_length=16)),
                ('lot_size', models.IntegerField(default=1)),
                ('tick_size', models.DecimalField(decimal_places=4, default=0.05, max_digits=8)),
            ],
            options={
                'indexes': [models.Index(fields=['exchange', 'tradingsymbol'], name='market_data_exchang_7da0b8_idx')],
                'unique_together': {('exchange', 'token')},
            },
        ),
        migrations.CreateModel(
            name='Candle',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('interval', models.CharField(max_length=8)),
                ('t', models.DateTimeField(db_index=True)),
                ('o', models.DecimalField(decimal_places=4, max_digits=14)),
                ('h', models.DecimalField(decimal_places=4, max_digits=14)),
                ('l', models.DecimalField(decimal_places=4, max_digits=14)),
                ('c', models.DecimalField(decimal_places=4, max_digits=14)),
                ('v', models.BigIntegerField()),
                ('symbol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candles', to='market_data.symbol')),
            ],
            options={
                'indexes': [models.Index(fields=['symbol', 'interval', '-t'], name='market_data_symbol__260a9e_idx')],
                'unique_together': {('symbol', 'interval', 't')},
            },
        ),
    ]
