# Generated by Django 5.1.15 on 2026-05-18 00:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market_data', '0001_initial'),
        ('tenants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BrokerPositionSnapshot',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('fetched_at', models.DateTimeField(db_index=True)),
                ('positions', models.JSONField(default=list)),
                ('holdings', models.JSONField(default=list)),
                ('margin', models.JSONField(default=dict)),
                ('ok', models.BooleanField(default=True)),
                ('error', models.CharField(blank=True, default='', max_length=512)),
            ],
            options={
                'ordering': ['-fetched_at'],
            },
        ),
        migrations.AddField(
            model_name='brokerlink',
            name='credential_blob',
            field=models.BinaryField(blank=True, help_text='Fernet-encrypted credential JSON (dev/local)', null=True),
        ),
        migrations.AddField(
            model_name='brokerlink',
            name='credential_meta',
            field=models.JSONField(blank=True, default=dict, help_text='Non-secret broker metadata (account id, user code, etc.)'),
        ),
        migrations.AddField(
            model_name='brokerlink',
            name='display_name',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='brokerlink',
            name='is_default',
            field=models.BooleanField(default=False, help_text='Primary account for new order placement'),
        ),
        migrations.AddField(
            model_name='brokerlink',
            name='last_error',
            field=models.CharField(blank=True, default='', max_length=512),
        ),
        migrations.AlterField(
            model_name='brokerlink',
            name='credential_arn',
            field=models.CharField(blank=True, default='', help_text='AWS Secrets Manager ARN (prod)', max_length=256),
        ),
        migrations.AlterField(
            model_name='brokerlink',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('expired', 'Expired'), ('disabled', 'Disabled'), ('errored', 'Errored')], default='active', max_length=16),
        ),
        migrations.AddIndex(
            model_name='brokerlink',
            index=models.Index(fields=['tenant', 'status'], name='broker_brok_tenant__17454b_idx'),
        ),
        migrations.AddField(
            model_name='brokerpositionsnapshot',
            name='link',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='snapshots', to='market_data.brokerlink'),
        ),
        migrations.AddField(
            model_name='brokerpositionsnapshot',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='tenants.tenant'),
        ),
        migrations.AddIndex(
            model_name='brokerpositionsnapshot',
            index=models.Index(fields=['tenant', 'link', '-fetched_at'], name='market_data_tenant__989ddd_idx'),
        ),
    ]
