# Generated by Django 5.1.15 on 2026-06-28 00:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market_data', '0003_pendingoauth'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockEdgeSnapshot',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('dataset', models.CharField(db_index=True, help_text='market_breadth | sector_rotation | fii_dii | fno_oi | …', max_length=40)),
                ('as_of_date', models.DateField(db_index=True)),
                ('captured_at', models.DateTimeField(auto_now_add=True)),
                ('source_url', models.URLField(blank=True, default='', max_length=512)),
                ('exchange', models.CharField(default='NSE', max_length=8)),
                ('raw', models.JSONField(default=dict, help_text='Full captured/normalized payload')),
                ('meta', models.JSONField(blank=True, default=dict, help_text='Capture metadata (columns, unit, scan id, etc.)')),
            ],
            options={
                'ordering': ['-as_of_date'],
                'indexes': [models.Index(fields=['dataset', '-as_of_date'], name='market_data_dataset_f5d698_idx')],
                'unique_together': {('dataset', 'as_of_date', 'exchange')},
            },
        ),
        migrations.CreateModel(
            name='StockEdgeBreadthRow',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('index_name', models.CharField(max_length=80)),
                ('constituent_count', models.IntegerField(blank=True, null=True)),
                ('rs_pos', models.FloatField(blank=True, help_text='% constituents with RS > 0', null=True)),
                ('sma20', models.FloatField(blank=True, help_text='% constituents above SMA20', null=True)),
                ('sma50', models.FloatField(blank=True, help_text='% constituents above SMA50', null=True)),
                ('sma100', models.FloatField(blank=True, help_text='% constituents above SMA100', null=True)),
                ('sma200', models.FloatField(blank=True, help_text='% constituents above SMA200', null=True)),
                ('as_of_date', models.DateField(db_index=True)),
                ('exchange', models.CharField(default='NSE', max_length=8)),
                ('snapshot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='breadth_rows', to='market_data.stockedgesnapshot')),
            ],
            options={
                'indexes': [models.Index(fields=['as_of_date', 'index_name'], name='market_data_as_of_d_6b77a7_idx')],
            },
        ),
    ]
