# Generated by Django 5.1.15 on 2026-06-28 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market_data', '0004_stockedgesnapshot_stockedgebreadthrow'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockedgesnapshot',
            name='refreshed_at',
            field=models.DateTimeField(auto_now=True, help_text='Last time this snapshot was re-pulled/updated in place'),
        ),
        migrations.AlterField(
            model_name='stockedgesnapshot',
            name='captured_at',
            field=models.DateTimeField(auto_now_add=True, help_text='First time this (dataset, day, exchange) was captured'),
        ),
    ]
