# Generated by Django 5.1.15 on 2026-06-28 01:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market_data', '0005_stockedgesnapshot_refreshed_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockEdgeScanRow',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('symbol', models.CharField(db_index=True, max_length=40)),
                ('name', models.CharField(blank=True, default='', max_length=160)),
                ('sector', models.CharField(blank=True, default='', max_length=80)),
                ('industry', models.CharField(blank=True, default='', max_length=160)),
                ('ltp', models.FloatField(blank=True, null=True)),
                ('change_pct', models.FloatField(blank=True, null=True)),
                ('market_cap_cr', models.FloatField(blank=True, help_text='Market cap in Rs. crore', null=True)),
                ('attrs', models.JSONField(blank=True, default=dict, help_text='Dataset-specific fields (scores, zones, flags, type, …)')),
                ('as_of_date', models.DateField(db_index=True)),
                ('exchange', models.CharField(default='NSE', max_length=8)),
                ('snapshot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scan_rows', to='market_data.stockedgesnapshot')),
            ],
            options={
                'indexes': [models.Index(fields=['as_of_date', 'symbol'], name='market_data_as_of_d_af526d_idx'), models.Index(fields=['snapshot', 'symbol'], name='market_data_snapsho_afd5e9_idx')],
            },
        ),
    ]
