# Generated by Django 5.2.11 on 2026-02-28 05:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PortfolioSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('capital', models.FloatField(help_text='Total capital in INR')),
                ('invested', models.FloatField(default=0.0, help_text='Currently invested amount')),
                ('available_cash', models.FloatField(help_text='Available cash for trading')),
                ('daily_pnl', models.FloatField(default=0.0, help_text='P&L for the day so far')),
                ('total_pnl', models.FloatField(default=0.0, help_text='Cumulative P&L across all sessions')),
                ('daily_loss', models.FloatField(default=0.0, help_text='Total losses for the day (positive number)')),
                ('open_positions', models.IntegerField(default=0)),
                ('open_positions_count', models.IntegerField(default=0, help_text='Alias for open_positions for compatibility')),
                ('snapshot_date', models.DateField(db_index=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-snapshot_date'],
                'get_latest_by': 'snapshot_date',
            },
        ),
        migrations.CreateModel(
            name='StrategyDoc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField(help_text='Strategy text — injected into planner prompt')),
                ('category', models.CharField(choices=[('RULE', 'Rule'), ('PATTERN', 'Pattern'), ('STRATEGY', 'Strategy'), ('NOTE', 'Note')], default='RULE', max_length=12)),
                ('is_active', models.BooleanField(default=True, help_text='Inactive docs are excluded from RAG')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['category', 'title'],
            },
        ),
        migrations.CreateModel(
            name='TradeJournal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(db_index=True, max_length=30)),
                ('side', models.CharField(choices=[('BUY', 'Buy'), ('SELL', 'Sell')], max_length=4)),
                ('entry_price', models.FloatField()),
                ('stop_loss', models.FloatField()),
                ('target', models.FloatField()),
                ('quantity', models.IntegerField()),
                ('reasoning', models.TextField(help_text='LLM rationale for the trade')),
                ('confidence', models.FloatField(default=0.0, help_text='Planner confidence 0-1')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('PLANNED', 'Planned'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('EXECUTED', 'Executed'), ('FILLED', 'Filled'), ('PARTIAL', 'Partial'), ('CANCELLED', 'Cancelled'), ('PAPER', 'Paper')], default='PENDING', max_length=12)),
                ('order_id', models.CharField(blank=True, default='', max_length=64)),
                ('fill_price', models.FloatField(blank=True, null=True)),
                ('fill_quantity', models.IntegerField(blank=True, null=True)),
                ('pnl', models.FloatField(blank=True, help_text='Realized P&L in INR', null=True)),
                ('pnl_percent', models.FloatField(blank=True, null=True)),
                ('risk_approved', models.BooleanField(default=False)),
                ('risk_reason', models.CharField(blank=True, default='', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('trade_date', models.DateField(db_index=True, help_text='Trading session date')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['symbol', 'trade_date'], name='trading_tra_symbol_6f1a44_idx'), models.Index(fields=['status'], name='trading_tra_status_61859c_idx')],
            },
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('PLANNER_REQ', 'Planner Request'), ('PLANNER_RES', 'Planner Response'), ('PLANNER_ERR', 'Planner Error'), ('RISK_APPROVE', 'Risk Approved'), ('RISK_REJECT', 'Risk Rejected'), ('EXECUTION', 'Execution'), ('RECONCILE', 'Reconciliation')], db_index=True, max_length=16)),
                ('symbol', models.CharField(blank=True, db_index=True, default='', max_length=30)),
                ('prompt', models.TextField(blank=True, default='', help_text='Full prompt sent to LLM')),
                ('response', models.TextField(blank=True, default='', help_text='Full LLM response (raw)')),
                ('model_name', models.CharField(blank=True, default='', max_length=64)),
                ('tokens_used', models.IntegerField(blank=True, null=True)),
                ('latency_ms', models.IntegerField(blank=True, help_text='LLM call latency in milliseconds', null=True)),
                ('risk_details', models.JSONField(blank=True, help_text='Full risk validation details', null=True)),
                ('execution_details', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('trade_journal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to='trading.tradejournal')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['event_type', 'created_at'], name='trading_aud_event_t_10316b_idx'), models.Index(fields=['symbol', 'created_at'], name='trading_aud_symbol_debe84_idx')],
            },
        ),
    ]
