# Generated by Django 5.2.11 on 2026-02-28 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='strategydoc',
            name='category',
            field=models.CharField(choices=[('ENTRY', 'Entry'), ('EXIT', 'Exit'), ('RISK', 'Risk'), ('SIZING', 'Sizing'), ('FILTER', 'Filter'), ('GENERAL', 'General'), ('RULE', 'Rule'), ('PATTERN', 'Pattern'), ('STRATEGY', 'Strategy')], default='RULE', max_length=12),
        ),
    ]
