# Generated by Django 6.0.2 on 2026-03-09 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0002_alter_strategydoc_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='StraddlePosition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('underlying', models.CharField(db_index=True, default='NIFTY', max_length=20)),
                ('strike', models.IntegerField(help_text='Strike price e.g. 24200')),
                ('expiry', models.DateField(help_text='Option expiry date')),
                ('lot_size', models.IntegerField(default=65, help_text='NIFTY lot size')),
                ('lots', models.IntegerField(default=1)),
                ('ce_symbol', models.CharField(help_text='e.g. NIFTY10MAR2624200CE', max_length=40)),
                ('ce_token', models.CharField(help_text='Angel One NFO token', max_length=20)),
                ('ce_sell_price', models.FloatField(help_text='Premium received when CE was sold')),
                ('ce_current_price', models.FloatField(default=0.0)),
                ('pe_symbol', models.CharField(help_text='e.g. NIFTY10MAR2624200PE', max_length=40)),
                ('pe_token', models.CharField(help_text='Angel One NFO token', max_length=20)),
                ('pe_sell_price', models.FloatField(help_text='Premium received when PE was sold')),
                ('pe_current_price', models.FloatField(default=0.0)),
                ('net_delta', models.FloatField(default=0.0)),
                ('current_pnl_inr', models.FloatField(default=0.0)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('PARTIAL', 'Partial'), ('HEDGED', 'Hedged'), ('CLOSED', 'Closed')], default='ACTIVE', max_length=10)),
                ('action_taken', models.CharField(choices=[('NONE', 'None'), ('HOLD', 'Hold'), ('CLOSE_BOTH', 'Close Both'), ('CLOSE_CE', 'Close Ce'), ('CLOSE_PE', 'Close Pe'), ('HEDGE_FUTURES', 'Hedge Futures'), ('ROLL', 'Roll')], default='NONE', max_length=20)),
                ('management_log', models.JSONField(blank=True, default=list, help_text='List of management events: [{time, action, nifty, pnl_inr, note, executed}]')),
                ('opened_at', models.DateTimeField(auto_now_add=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('trade_date', models.DateField(db_index=True)),
            ],
            options={
                'ordering': ['-opened_at'],
                'indexes': [models.Index(fields=['underlying', 'strike', 'expiry'], name='trading_str_underly_dc2547_idx'), models.Index(fields=['status'], name='trading_str_status_3fa50b_idx')],
            },
        ),
    ]
