# Generated by Django 5.2.11 on 2026-03-16 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0004_systemcontrol_tradernote'),
    ]

    operations = [
        migrations.CreateModel(
            name='WatchlistEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(db_index=True, max_length=30)),
                ('scan_date', models.DateField(db_index=True)),
                ('score', models.FloatField(help_text='Premarket scanner score 0-100')),
                ('bias', models.CharField(default='NEUTRAL', max_length=10)),
                ('setups', models.JSONField(default=list, help_text='List of potential setup types')),
                ('prev_high', models.FloatField(default=0.0)),
                ('prev_low', models.FloatField(default=0.0)),
                ('prev_close', models.FloatField(default=0.0)),
                ('prev_atr', models.FloatField(default=0.0)),
                ('orb_high', models.FloatField(blank=True, null=True)),
                ('orb_low', models.FloatField(blank=True, null=True)),
                ('vwap', models.FloatField(blank=True, null=True)),
                ('outcome', models.CharField(choices=[('WATCHING', 'Watching'), ('TRIGGERED', 'Triggered'), ('TRADED', 'Traded'), ('SKIPPED', 'Skipped'), ('NO_SIGNAL', 'No Signal')], default='WATCHING', max_length=12)),
                ('triggered_setup', models.CharField(blank=True, default='', max_length=20)),
                ('reason', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-scan_date', '-score'],
                'indexes': [models.Index(fields=['scan_date', 'score'], name='trading_wat_scan_da_59ce35_idx')],
                'unique_together': {('symbol', 'scan_date')},
            },
        ),
    ]
