# Generated by Django 6.0.2 on 2026-03-19 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0005_add_watchlist_entry'),
    ]

    operations = [
        migrations.AddField(
            model_name='straddleposition',
            name='realized_pnl',
            field=models.FloatField(default=0.0, help_text='Accumulated P&L from rolled/closed legs'),
        ),
        migrations.AlterField(
            model_name='straddleposition',
            name='action_taken',
            field=models.CharField(choices=[('NONE', 'None'), ('HOLD', 'Hold'), ('CLOSE_BOTH', 'Close Both'), ('CLOSE_CE', 'Close Ce'), ('CLOSE_PE', 'Close Pe'), ('ROLL_PE', 'Roll Pe'), ('ROLL_CE', 'Roll Ce'), ('HEDGE_FUTURES', 'Hedge Futures'), ('REENTER', 'Reenter')], default='NONE', max_length=20),
        ),
    ]
