# Generated by Django 5.1.15 on 2026-05-06 20:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0006_add_realized_pnl'),
    ]

    operations = [
        migrations.CreateModel(
            name='SignalLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(db_index=True, max_length=30)),
                ('signal_date', models.DateField(db_index=True)),
                ('signal_time', models.DateTimeField()),
                ('source', models.CharField(choices=[('SCREENER', 'Screener'), ('OK_SCANNER', 'Ok Scanner'), ('PREMARKET', 'Premarket')], max_length=16)),
                ('strategy', models.CharField(max_length=40)),
                ('side', models.CharField(max_length=5)),
                ('entry_price', models.FloatField()),
                ('stoploss', models.FloatField()),
                ('target', models.FloatField()),
                ('confidence', models.FloatField(default=0.0)),
                ('risk_reward', models.FloatField(default=0.0)),
                ('reasons', models.JSONField(default=list)),
                ('indicators', models.JSONField(default=dict)),
                ('outcome', models.CharField(choices=[('PENDING', 'Pending'), ('TRADED', 'Traded'), ('REJECTED', 'Rejected'), ('SKIPPED', 'Skipped'), ('EXPIRED', 'Expired')], default='PENDING', max_length=10)),
                ('outcome_reason', models.TextField(blank=True, default='')),
                ('eod_price', models.FloatField(blank=True, null=True)),
                ('max_favorable_move', models.FloatField(blank=True, help_text='Best intraday price move in signal direction after entry', null=True)),
                ('max_adverse_move', models.FloatField(blank=True, help_text='Worst intraday price move against signal direction', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('trade_journal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='signal_logs', to='trading.tradejournal')),
            ],
            options={
                'ordering': ['-signal_time'],
                'indexes': [models.Index(fields=['signal_date', 'symbol'], name='trading_sig_signal__b6f5e7_idx'), models.Index(fields=['source', 'signal_date'], name='trading_sig_source_512ab3_idx'), models.Index(fields=['outcome'], name='trading_sig_outcome_3e9561_idx')],
            },
        ),
    ]
