"""StockEdge CSV-export ingestion — generic parser, model, and command.

Uses small embedded fixtures mirroring the real exports (Cannon strategy +
Nifty 500 momentum scores) so the suite never depends on local Downloads.
"""
from __future__ import annotations

from datetime import date

import pytest
from django.core.management import call_command

from apps.market_data.integrations.stockedge.csv_ingest import (
    parse_stockedge_csv,
    summarize_csv,
)
from apps.market_data.models import StockEdgeScanRow, StockEdgeSnapshot

pytestmark = pytest.mark.django_db

STRATEGY_CSV = (
    "Cannon (Momentum),\n"
    "Date: 25-Jun-2026,\n"
    "Major Stocks,\n"
    "Generated by and for: x@y.com,\n"
    "\n"
    "Stock Name,Symbol,Exch,LTP,Chg%,Sector Name,Industry Name,Type,"
    "Closing Above Previous High,RSI Overbought Zone,Symbol with Comma for External Upload\n"
    'ICICI Bank Ltd.,ICICIBANK,NSE,1387.50,1.01,Banking,Bank - Private,PerfectMatch,Y,Y,"ICICIBANK,"\n'
    'Aegis Logistics Ltd.,AEGISLOG,NSE,1140.65,7.31,Trading,Trading,AlmostThere,Y,,"AEGISLOG,"\n'
)

SCORES_CSV = (
    "Index: Nifty 500,\n"
    "Date: 25-Jun-2026,\n"
    "Generated by and for: x@y.com,\n"
    "\n"
    "Name,Symbol,Sector,Industry,Market Cap (Rs. Cr.),LTP,Change%,"
    "1M Score,1M Score - Zone,3M Score,3M Score - Zone,6M Score,6M Score - Zone,"
    "Symbol with Comma for External Upload\n"
    'Reliance Industries Ltd.,RELIANCE,Crude Oil,Refineries,1783926.92,1318.10,0.34,'
    '38,Bearish,42,Neutral,42,Neutral,"RELIANCE, "\n'
    'HDFC Bank Ltd.,HDFCBANK,Banking,Bank - Private,1226022.68,796.30,0.39,'
    '77,Bullish,58,Neutral,40,Bearish,"HDFCBANK, "\n'
)


# ── parser: strategy export ───────────────────────────────────────────
def test_parse_strategy_csv():
    p = parse_stockedge_csv(STRATEGY_CSV)
    assert p["kind"] == "strategy"
    assert p["dataset"] == "strategy_cannon_momentum"
    assert p["as_of_date"] == "2026-06-25"
    assert p["generated_for"] == "x@y.com"
    assert len(p["rows"]) == 2

    icici = p["rows"][0]
    # common columns promoted to real fields
    assert icici["symbol"] == "ICICIBANK"
    assert icici["name"] == "ICICI Bank Ltd."
    assert icici["sector"] == "Banking"
    assert icici["ltp"] == 1387.50
    assert icici["change_pct"] == 1.01
    assert icici["exchange"] == "NSE"
    # dataset-specific → attrs, with Y/blank coerced to bool
    assert icici["attrs"]["type"] == "PerfectMatch"
    assert icici["attrs"]["closing_above_previous_high"] is True
    assert icici["attrs"]["rsi_overbought_zone"] is True
    # AEGISLOG had a blank RSI flag → None (falsy)
    assert p["rows"][1]["attrs"]["rsi_overbought_zone"] is None
    # the external-upload helper column is dropped entirely
    assert not any("external" in k for k in icici["attrs"])


# ── parser: scores export ─────────────────────────────────────────────
def test_parse_scores_csv():
    p = parse_stockedge_csv(SCORES_CSV)
    assert p["kind"] == "momentum_scores"
    assert p["dataset"] == "momentum_scores_nifty_500"
    assert len(p["rows"]) == 2

    rel = p["rows"][0]
    assert rel["symbol"] == "RELIANCE"
    assert rel["market_cap_cr"] == 1783926.92
    assert rel["attrs"]["1m_score"] == 38
    assert rel["attrs"]["1m_score_zone"] == "Bearish"
    assert rel["attrs"]["6m_score_zone"] == "Neutral"


def test_summarize_scores_zones():
    s = summarize_csv(parse_stockedge_csv(SCORES_CSV))
    assert s["kind"] == "momentum_scores"
    assert s["row_count"] == 2
    # RELIANCE Bearish + HDFCBANK Bullish on the 1M horizon
    assert s["zones_1m"] == {"Bullish": 1, "Neutral": 0, "Bearish": 1}


@pytest.mark.parametrize("bad", ["", "just,one,line\n", "no header here\n\n\n"])
def test_parse_rejects_malformed(bad):
    with pytest.raises(ValueError):
        parse_stockedge_csv(bad)


# ── command: persistence ──────────────────────────────────────────────
def test_command_persists_scan_rows(tmp_path):
    f = tmp_path / "scores.csv"
    f.write_text(SCORES_CSV, encoding="utf-8")
    call_command("pull_stockedge_csv", "--file", str(f))

    snap = StockEdgeSnapshot.objects.get(dataset="momentum_scores_nifty_500")
    assert snap.as_of_date == date(2026, 6, 25)
    assert snap.scan_rows.count() == 2
    assert snap.meta["kind"] == "momentum_scores"
    # queryable: attrs JSON survives the round-trip
    hdfc = StockEdgeScanRow.objects.get(symbol="HDFCBANK")
    assert hdfc.attrs["1m_score_zone"] == "Bullish"
    assert hdfc.market_cap_cr == 1226022.68


def test_command_upserts_on_repull(tmp_path):
    f = tmp_path / "cannon.csv"
    f.write_text(STRATEGY_CSV, encoding="utf-8")
    call_command("pull_stockedge_csv", "--file", str(f))
    call_command("pull_stockedge_csv", "--file", str(f))

    assert StockEdgeSnapshot.objects.filter(dataset="strategy_cannon_momentum").count() == 1
    snap = StockEdgeSnapshot.objects.get(dataset="strategy_cannon_momentum")
    assert snap.scan_rows.count() == 2  # children replaced, not duplicated
