# Generated by Django 5.1.15 on 2026-05-11 05:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('agents_core', '0001_initial'),
        ('orders', '0001_initial'),
        ('tenants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('ts', models.DateTimeField(db_index=True, help_text='Event time (may differ from row created_at)')),
                ('type', models.CharField(choices=[('workflow.started', 'Workflow Started'), ('workflow.step.started', 'Workflow Step Started'), ('workflow.step.completed', 'Workflow Step Completed'), ('workflow.step.failed', 'Workflow Step Failed'), ('workflow.completed', 'Workflow Completed'), ('workflow.cancelled', 'Workflow Cancelled'), ('llm.request', 'Llm Request'), ('llm.response', 'Llm Response'), ('llm.error', 'Llm Error'), ('risk.approved', 'Risk Approved'), ('risk.rejected', 'Risk Rejected'), ('order.queued', 'Order Queued'), ('order.sent', 'Order Sent'), ('order.filled', 'Order Filled'), ('order.partial', 'Order Partial'), ('order.cancelled', 'Order Cancelled'), ('order.rejected', 'Order Rejected'), ('order.failed', 'Order Failed'), ('trade.planned', 'Trade Planned'), ('trade.opened', 'Trade Opened'), ('trade.closed', 'Trade Closed'), ('trade.sl_hit', 'Trade Sl Hit'), ('trade.target_hit', 'Trade Tgt Hit'), ('trade.trailed', 'Trade Trailed'), ('straddle.opened', 'Straddle Opened'), ('straddle.leg_rolled', 'Straddle Leg Rolled'), ('straddle.hedged', 'Straddle Hedged'), ('straddle.closed', 'Straddle Closed'), ('pyramid.add', 'Pyramid Add'), ('pyramid.exit', 'Pyramid Exit'), ('signal.fired', 'Signal Fired'), ('signal.expired', 'Signal Expired'), ('signal.enriched', 'Signal Enriched'), ('system.ai_paused', 'System Ai Paused'), ('system.ai_resumed', 'System Ai Resumed'), ('system.kill_switch', 'System Kill Switch'), ('broker.linked', 'Broker Linked'), ('broker.expired', 'Broker Expired')], db_index=True, max_length=40)),
                ('severity', models.CharField(choices=[('info', 'Info'), ('warn', 'Warn'), ('error', 'Error')], default='info', max_length=8)),
                ('actor_kind', models.CharField(choices=[('user', 'User'), ('workflow', 'Workflow'), ('risk_engine', 'Risk Engine'), ('broker', 'Broker'), ('system', 'System')], default='workflow', max_length=16)),
                ('step_name', models.CharField(blank=True, default='', max_length=64)),
                ('trade_id', models.UUIDField(blank=True, db_index=True, help_text='FK to trading.Trade (added when that model exists)', null=True)),
                ('signal_id', models.BigIntegerField(blank=True, db_index=True, help_text='FK to strategies.Signal (added later)', null=True)),
                ('payload', models.JSONField(blank=True, default=dict, help_text='Type-specific structured body (prompt, risk breakdown, etc.)')),
                ('text', models.TextField(blank=True, default='', help_text='Human-readable line for the timeline UI')),
                ('ip', models.GenericIPAddressField(blank=True, null=True)),
                ('request_id', models.CharField(blank=True, default='', max_length=64)),
                ('actor_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='orders.order')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='tenants.tenant')),
                ('workflow_run', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='agents_core.agentrun')),
            ],
            options={
                'ordering': ['-ts'],
                'indexes': [models.Index(fields=['tenant', '-ts'], name='events_even_tenant__1f4ff8_idx'), models.Index(fields=['tenant', 'type', '-ts'], name='events_even_tenant__0078c1_idx'), models.Index(fields=['tenant', 'workflow_run', '-ts'], name='events_even_tenant__07b331_idx'), models.Index(fields=['tenant', 'trade_id', '-ts'], name='events_even_tenant__967879_idx')],
            },
        ),
    ]
