# Generated by Django 5.1.15 on 2026-05-11 06:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
        ('trading', '0002_trades'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='options_position',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='trading.optionsposition'),
        ),
        migrations.AlterField(
            model_name='event',
            name='signal_id',
            field=models.BigIntegerField(blank=True, db_index=True, help_text='Soft FK to strategies.Signal.id', null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='trade_id',
            field=models.UUIDField(blank=True, db_index=True, help_text='Soft FK to trades.Trade.id', null=True),
        ),
    ]
