# Generated by Django 5.1.15 on 2026-06-27 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_event_options_position_alter_event_signal_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='type',
            field=models.CharField(choices=[('workflow.started', 'Workflow Started'), ('workflow.step.started', 'Workflow Step Started'), ('workflow.step.completed', 'Workflow Step Completed'), ('workflow.step.failed', 'Workflow Step Failed'), ('workflow.completed', 'Workflow Completed'), ('workflow.cancelled', 'Workflow Cancelled'), ('llm.request', 'Llm Request'), ('llm.response', 'Llm Response'), ('llm.error', 'Llm Error'), ('risk.approved', 'Risk Approved'), ('risk.rejected', 'Risk Rejected'), ('order.queued', 'Order Queued'), ('order.sent', 'Order Sent'), ('order.filled', 'Order Filled'), ('order.partial', 'Order Partial'), ('order.cancelled', 'Order Cancelled'), ('order.rejected', 'Order Rejected'), ('order.failed', 'Order Failed'), ('trade.planned', 'Trade Planned'), ('trade.opened', 'Trade Opened'), ('trade.closed', 'Trade Closed'), ('trade.sl_hit', 'Trade Sl Hit'), ('trade.target_hit', 'Trade Tgt Hit'), ('trade.trailed', 'Trade Trailed'), ('trade.feedback', 'Trade Feedback'), ('straddle.opened', 'Straddle Opened'), ('straddle.leg_rolled', 'Straddle Leg Rolled'), ('straddle.hedged', 'Straddle Hedged'), ('straddle.closed', 'Straddle Closed'), ('pyramid.add', 'Pyramid Add'), ('pyramid.exit', 'Pyramid Exit'), ('signal.fired', 'Signal Fired'), ('signal.expired', 'Signal Expired'), ('signal.enriched', 'Signal Enriched'), ('system.ai_paused', 'System Ai Paused'), ('system.ai_resumed', 'System Ai Resumed'), ('system.kill_switch', 'System Kill Switch'), ('broker.linked', 'Broker Linked'), ('broker.expired', 'Broker Expired')], db_index=True, max_length=40),
        ),
    ]
