# Generated by Django 5.1.15 on 2026-05-11 06:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('strategies', '0001_initial'),
        ('tenants', '0001_initial'),
        ('trading', '0002_trades'),
    ]

    operations = [
        migrations.CreateModel(
            name='Signal',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('symbol', models.CharField(db_index=True, max_length=30)),
                ('signal_date', models.DateField(db_index=True)),
                ('signal_time', models.DateTimeField()),
                ('source', models.CharField(choices=[('SCREENER', 'Screener'), ('OK_SCANNER', 'Ok Scanner'), ('PREMARKET', 'Premarket')], max_length=16)),
                ('strategy', models.CharField(max_length=40)),
                ('side', models.CharField(max_length=5)),
                ('entry_price', models.FloatField()),
                ('stoploss', models.FloatField()),
                ('target', models.FloatField()),
                ('confidence', models.FloatField(default=0.0)),
                ('risk_reward', models.FloatField(default=0.0)),
                ('reasons', models.JSONField(default=list)),
                ('indicators', models.JSONField(default=dict)),
                ('outcome', models.CharField(choices=[('PENDING', 'Pending'), ('TRADED', 'Traded'), ('REJECTED', 'Rejected'), ('SKIPPED', 'Skipped'), ('EXPIRED', 'Expired')], default='PENDING', max_length=10)),
                ('outcome_reason', models.TextField(blank=True, default='')),
                ('eod_price', models.FloatField(blank=True, null=True)),
                ('max_favorable_move', models.FloatField(blank=True, null=True)),
                ('max_adverse_move', models.FloatField(blank=True, null=True)),
                ('legacy_signal_log_id', models.IntegerField(blank=True, db_index=True, null=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='tenants.tenant')),
                ('trade', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='signals', to='trading.trade')),
            ],
            options={
                'ordering': ['-signal_time'],
                'indexes': [models.Index(fields=['tenant', 'signal_date', 'symbol'], name='strategies__tenant__217557_idx'), models.Index(fields=['tenant', 'source', 'signal_date'], name='strategies__tenant__fbe04a_idx'), models.Index(fields=['tenant', 'outcome'], name='strategies__tenant__d4475f_idx')],
            },
        ),
        migrations.CreateModel(
            name='WatchlistEntry',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('symbol', models.CharField(db_index=True, max_length=30)),
                ('scan_date', models.DateField(db_index=True)),
                ('score', models.FloatField(help_text='Premarket scanner score 0-100')),
                ('bias', models.CharField(default='NEUTRAL', max_length=10)),
                ('setups', models.JSONField(default=list)),
                ('prev_high', models.FloatField(default=0.0)),
                ('prev_low', models.FloatField(default=0.0)),
                ('prev_close', models.FloatField(default=0.0)),
                ('prev_atr', models.FloatField(default=0.0)),
                ('orb_high', models.FloatField(blank=True, null=True)),
                ('orb_low', models.FloatField(blank=True, null=True)),
                ('vwap', models.FloatField(blank=True, null=True)),
                ('outcome', models.CharField(choices=[('WATCHING', 'Watching'), ('TRIGGERED', 'Triggered'), ('TRADED', 'Traded'), ('SKIPPED', 'Skipped'), ('NO_SIGNAL', 'No Signal')], default='WATCHING', max_length=12)),
                ('triggered_setup', models.CharField(blank=True, default='', max_length=20)),
                ('reason', models.TextField(blank=True, default='')),
                ('legacy_watchlist_id', models.IntegerField(blank=True, db_index=True, null=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='tenants.tenant')),
            ],
            options={
                'ordering': ['-scan_date', '-score'],
                'indexes': [models.Index(fields=['tenant', 'scan_date', 'score'], name='strategies__tenant__8e4422_idx')],
                'unique_together': {('tenant', 'symbol', 'scan_date')},
            },
        ),
    ]
