# Generated by Django 5.1.15 on 2026-05-19 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('strategies', '0002_signal_watchlistentry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signal',
            name='source',
            field=models.CharField(choices=[('SCREENER', 'Screener'), ('OK_SCANNER', 'Ok Scanner'), ('PREMARKET', 'Premarket'), ('TRADINGVIEW', 'Tradingview')], max_length=16),
        ),
    ]
