# Generated by Django 5.1.15 on 2026-06-28 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('strategies', '0003_alter_signal_source'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signal',
            name='source',
            field=models.CharField(choices=[('SCREENER', 'Screener'), ('OK_SCANNER', 'Ok Scanner'), ('PREMARKET', 'Premarket'), ('TRADINGVIEW', 'Tradingview'), ('STOCKEDGE', 'Stockedge')], max_length=16),
        ),
    ]
