# Generated by Django 5.1.15 on 2026-06-26 22:25

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market_data', '0003_pendingoauth'),
        ('tenants', '0001_initial'),
        ('trading', '0002_trades'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='order',
            constraint=models.UniqueConstraint(condition=models.Q(('idempotency_key', ''), _negated=True), fields=('tenant', 'idempotency_key'), name='uniq_order_tenant_idempotency_key'),
        ),
    ]
