# Generated by Django 5.1.15 on 2026-04-18 12:33

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('broker', '0001_initial'),
        ('portfolio', '0001_initial'),
        ('tenants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('symbol', models.CharField(max_length=80)),
                ('side', models.CharField(choices=[('BUY', 'Buy'), ('SELL', 'Sell')], max_length=4)),
                ('qty', models.IntegerField()),
                ('order_type', models.CharField(default='MARKET', max_length=16)),
                ('product', models.CharField(choices=[('INTRADAY', 'Intraday'), ('DELIVERY', 'Delivery'), ('CARRYFORWARD', 'Carryforward')], default='INTRADAY', max_length=16)),
                ('price', models.DecimalField(blank=True, decimal_places=4, max_digits=14, null=True)),
                ('sl', models.DecimalField(blank=True, decimal_places=4, max_digits=14, null=True)),
                ('tp', models.DecimalField(blank=True, decimal_places=4, max_digits=14, null=True)),
                ('broker_order_id', models.CharField(blank=True, max_length=80)),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('sent', 'Sent'), ('open', 'Open'), ('filled', 'Filled'), ('cancelled', 'Cancelled'), ('rejected', 'Rejected'), ('failed', 'Failed')], default='queued', max_length=16)),
                ('idempotency_key', models.CharField(blank=True, db_index=True, max_length=128)),
                ('origin', models.CharField(default='ui', max_length=32)),
                ('error', models.TextField(blank=True)),
                ('broker_link', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='broker.brokerlink')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('portfolio', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='portfolio.portfolio')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='tenants.tenant')),
            ],
        ),
        migrations.CreateModel(
            name='OutboxEvent',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('payload', models.JSONField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_flight', 'In Flight'), ('succeeded', 'Succeeded'), ('failed', 'Failed'), ('dlq', 'Dlq')], default='pending', max_length=16)),
                ('attempts', models.IntegerField(default=0)),
                ('last_error', models.TextField(blank=True)),
                ('next_run_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='orders.order')),
            ],
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['tenant', 'status', '-created_at'], name='orders_orde_tenant__1d191c_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['tenant', 'portfolio', '-created_at'], name='orders_orde_tenant__34015e_idx'),
        ),
        migrations.AddIndex(
            model_name='outboxevent',
            index=models.Index(fields=['status', 'next_run_at'], name='orders_outb_status_7ffd84_idx'),
        ),
    ]
