# Generated by Django 5.1.15 on 2026-04-18 12:33

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('broker', '0001_initial'),
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(default='Default', max_length=80)),
                ('capital', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=16)),
                ('used_capital', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=16)),
                ('realized_pnl', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=16)),
                ('day_pnl', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=16)),
                ('mode', models.CharField(default='paper', max_length=10)),
                ('broker_link', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='portfolios', to='broker.brokerlink')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='tenants.tenant')),
            ],
        ),
        migrations.CreateModel(
            name='PortfolioSnapshot',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('captured_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('equity', models.DecimalField(decimal_places=2, max_digits=16)),
                ('day_pnl', models.DecimalField(decimal_places=2, max_digits=16)),
                ('unrealized_pnl', models.DecimalField(decimal_places=2, max_digits=16)),
                ('open_positions', models.IntegerField()),
                ('portfolio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='snapshots', to='portfolio.portfolio')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='tenants.tenant')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('symbol', models.CharField(max_length=80)),
                ('side', models.CharField(max_length=4)),
                ('qty', models.IntegerField()),
                ('avg_price', models.DecimalField(decimal_places=4, max_digits=14)),
                ('last_ltp', models.DecimalField(blank=True, decimal_places=4, max_digits=14, null=True)),
                ('sl', models.DecimalField(blank=True, decimal_places=4, max_digits=14, null=True)),
                ('tp', models.DecimalField(blank=True, decimal_places=4, max_digits=14, null=True)),
                ('unrealized_pnl', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=16)),
                ('status', models.CharField(choices=[('open', 'Open'), ('closed', 'Closed')], default='open', max_length=10)),
                ('opened_at', models.DateTimeField(auto_now_add=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('portfolio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='positions', to='portfolio.portfolio')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='tenants.tenant')),
            ],
        ),
        migrations.AddIndex(
            model_name='portfolio',
            index=models.Index(fields=['tenant', 'mode'], name='portfolio_p_tenant__edc91b_idx'),
        ),
        migrations.AddIndex(
            model_name='position',
            index=models.Index(fields=['tenant', 'portfolio', 'status'], name='portfolio_p_tenant__a3ca52_idx'),
        ),
        migrations.AddIndex(
            model_name='position',
            index=models.Index(fields=['tenant', 'symbol'], name='portfolio_p_tenant__130ef3_idx'),
        ),
    ]
