# Generated by Django 5.1.15 on 2026-05-06 20:26

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='position',
            name='exchange',
            field=models.CharField(default='NSE', max_length=8),
        ),
        migrations.AddField(
            model_name='position',
            name='exit_price',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=14, null=True),
        ),
        migrations.AddField(
            model_name='position',
            name='realized_pnl',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=16),
        ),
        migrations.AddIndex(
            model_name='position',
            index=models.Index(fields=['tenant', 'portfolio', 'opened_at'], name='portfolio_p_tenant__9d5754_idx'),
        ),
    ]
