"""Parse official StockEdge CSV exports (the Download button on any page).

The download path is the cleanest, most ToS-defensible way to get StockEdge
data: it's the platform's own export, produced inside a logged-in session. Every
export shares one shape::

    <Title / Index>,
    Date: 25-Jun-2026,
    [optional filter line(s)],
    Generated by and for: <email>,
                                <-- blank line
    Col A,Col B,Col C,...        <-- real header row
    val,val,val,...              <-- data rows

This module is pure (no Django/Playwright): text in → normalized dict out, so it
is trivially unit-testable and reusable from the management command or a future
CDP-attached download harness.

Two real exports drove the design:
  * Trading strategies (e.g. *Cannon (Momentum)*): per-stock with a ``Type``
    (PerfectMatch/AlmostThere) and Y/blank criteria flags.
  * Stock-wise scores (e.g. *Nifty 500 Momentum Scores*): per-stock 1M/3M/6M
    score + Bullish/Neutral/Bearish zone + market cap.

Common stock columns are promoted to real fields; everything dataset-specific is
preserved in ``attrs`` so one model serves every stock-list export.
"""
from __future__ import annotations

import csv
import io
import re
from datetime import datetime
from typing import Any

# Header label → normalized common field. Matched case-insensitively on the
# stripped label. Anything not here lands in ``attrs``.
_COMMON = {
    "symbol": "symbol",
    "name": "name",
    "stock name": "name",
    "sector": "sector",
    "sector name": "sector",
    "industry": "industry",
    "industry name": "industry",
    "exch": "exchange",
    "exchange": "exchange",
    "ltp": "ltp",
    "chg%": "change_pct",
    "change%": "change_pct",
    "market cap (rs. cr.)": "market_cap_cr",
}
# Columns we drop entirely (StockEdge's external-upload helper column).
_DROP = {"symbol with comma for external upload"}

_NUMERIC_FIELDS = {"ltp", "change_pct", "market_cap_cr"}


def _to_float(value: Any) -> float | None:
    if value is None:
        return None
    s = str(value).strip().replace(",", "")
    if not s or s in {"-", "NA", "N/A"}:
        return None
    try:
        return float(s)
    except ValueError:
        return None


def _coerce_attr(value: str) -> Any:
    """Coerce a raw attr cell: numbers → number, Y/blank → bool, else string."""
    s = (value or "").strip()
    if s == "":
        return None
    if s in {"Y", "Yes", "TRUE", "True"}:
        return True
    if s in {"N", "No", "FALSE", "False"}:
        return False
    if re.fullmatch(r"-?\d+", s):
        return int(s)
    if re.fullmatch(r"-?\d+\.\d+", s):
        return float(s)
    return s


def _attr_key(label: str) -> str:
    """Slugify a header label into a stable snake_case attr key."""
    key = label.strip().lower()
    key = re.sub(r"[%()./]", " ", key)
    key = re.sub(r"[^a-z0-9]+", "_", key).strip("_")
    return key


def _parse_date(meta_lines: list[str]) -> str | None:
    """Pull 'Date: 25-Jun-2026' (or ISO/DD-MM-YYYY) from the metadata, → ISO."""
    for line in meta_lines:
        m = re.search(r"date\s*:\s*(.+)", line, re.I)
        if not m:
            continue
        raw = m.group(1).strip().rstrip(",").strip()
        for fmt in ("%d-%b-%Y", "%d-%m-%Y", "%Y-%m-%d", "%d/%m/%Y", "%d-%B-%Y"):
            try:
                return datetime.strptime(raw, fmt).date().isoformat()
            except ValueError:
                continue
    return None


def _slug(text: str, maxlen: int = 30) -> str:
    s = re.sub(r"[^a-z0-9]+", "_", text.strip().lower()).strip("_")
    return s[:maxlen]


def detect_dataset(meta_lines: list[str], header: list[str]) -> tuple[str, str]:
    """Return ``(dataset_slug, kind)`` for a parsed export.

    ``kind`` ∈ {'momentum_scores', 'strategy', 'scan', 'generic'}. The slug
    encodes the scope (index/strategy) so distinct exports get distinct snapshot
    lineages, e.g. ``momentum_scores_nifty500`` / ``strategy_cannon_momentum``.
    """
    hset = {h.strip().lower() for h in header}
    title = (meta_lines[0].strip().rstrip(",") if meta_lines else "").strip()
    index_line = next((l for l in meta_lines if re.match(r"\s*index\s*:", l, re.I)), "")
    scope = ""
    if index_line:
        scope = _slug(re.sub(r"\s*index\s*:\s*", "", index_line, flags=re.I).rstrip(","))

    if any("score" in h for h in hset):
        return (f"momentum_scores_{scope}".rstrip("_") or "momentum_scores", "momentum_scores")
    if "type" in hset:  # strategy export carries PerfectMatch/AlmostThere
        return (f"strategy_{_slug(title)}".rstrip("_") or "strategy", "strategy")
    return (_slug(title) or "stockedge_scan", "scan")


def parse_stockedge_csv(text: str) -> dict:
    """Parse a StockEdge CSV export string into a normalized payload.

    Returns::

        {
          "dataset": "momentum_scores_nifty500",
          "kind": "momentum_scores",
          "as_of_date": "2026-06-25",     # or None if absent
          "title": "Index: Nifty 500",
          "meta_lines": [...],
          "generated_for": "<email>",
          "columns": [...common+attr field names...],
          "rows": [ {symbol, name, sector, industry, ltp, change_pct,
                     market_cap_cr, exchange, attrs:{...}}, ... ],
        }

    Raises ``ValueError`` if no header/data rows can be located.
    """
    raw_rows = list(csv.reader(io.StringIO(text)))
    if not raw_rows:
        raise ValueError("empty CSV")

    # Header = first row with >3 non-empty cells; metadata = the lines before it.
    hdr_i = next(
        (i for i, r in enumerate(raw_rows) if len([c for c in r if c.strip()]) > 3),
        None,
    )
    if hdr_i is None:
        raise ValueError("could not locate a header row (>3 columns)")

    meta_lines = [r[0].strip() for r in raw_rows[:hdr_i] if r and r[0].strip()]
    header = [h.strip() for h in raw_rows[hdr_i]]
    data = [r for r in raw_rows[hdr_i + 1:] if any(c.strip() for c in r)]
    if not data:
        raise ValueError("no data rows after header")

    generated_for = next(
        (re.sub(r".*for\s*:\s*", "", l, flags=re.I).rstrip(",").strip()
         for l in meta_lines if "generated by" in l.lower()),
        "",
    )
    dataset, kind = detect_dataset(meta_lines, header)
    as_of = _parse_date(meta_lines)

    rows: list[dict] = []
    for raw in data:
        rec = {header[i].strip(): (raw[i] if i < len(raw) else "")
               for i in range(len(header))}
        row: dict[str, Any] = {
            "symbol": "", "name": "", "sector": "", "industry": "",
            "ltp": None, "change_pct": None, "market_cap_cr": None,
            "exchange": "NSE", "attrs": {},
        }
        for label, value in rec.items():
            low = label.strip().lower()
            if low in _DROP:
                continue
            if low in _COMMON:
                field = _COMMON[low]
                if field in _NUMERIC_FIELDS:
                    row[field] = _to_float(value)
                else:
                    row[field] = (value or "").strip()
            else:
                row["attrs"][_attr_key(label)] = _coerce_attr(value)
        if not row["symbol"]:
            continue  # skip blank/footer rows
        rows.append(row)

    columns = list(dict.fromkeys(
        [_COMMON.get(h.strip().lower(), _attr_key(h))
         for h in header if h.strip().lower() not in _DROP]
    ))
    return {
        "dataset": dataset,
        "kind": kind,
        "as_of_date": as_of,
        "title": meta_lines[0] if meta_lines else "",
        "meta_lines": meta_lines,
        "generated_for": generated_for,
        "columns": columns,
        "rows": rows,
    }


def summarize_csv(parsed: dict) -> dict:
    """Small, kind-aware highlight for the command output."""
    rows = parsed.get("rows", [])
    kind = parsed.get("kind")
    out = {"kind": kind, "row_count": len(rows)}
    if kind == "momentum_scores":
        def zone_counts(key):
            c = {"Bullish": 0, "Neutral": 0, "Bearish": 0}
            for r in rows:
                z = r["attrs"].get(key)
                if z in c:
                    c[z] += 1
            return c
        out["zones_1m"] = zone_counts("1m_score_zone")
        out["zones_3m"] = zone_counts("3m_score_zone")
        out["zones_6m"] = zone_counts("6m_score_zone")
    elif kind == "strategy":
        types: dict[str, int] = {}
        for r in rows:
            t = r["attrs"].get("type") or "?"
            types[t] = types.get(t, 0) + 1
        out["by_type"] = types
    return out
