from django.urls import path
from apps.market_data.api.views import (
    BasketView,
    CandleView,
    DepthImbalanceView,
    FIIDIIFlowView,
    First5MinView,
    GapFillView,
    LiquidityMapView,
    MarketPulseView,
    NewsShockView,
    OKBacktestView,
    ORBFailureView,
    ORBView,
    PyramidView,
    SectorDispersionView,
    SectorRotationView,
    SectorRRGView,
    Second5MinView,
    SetupPreviewView,
    ShortlistView,
    SwingScannerView,
    SymbolSearchView,
    TapeSpeedView,
    VolRegimeView,
    VWAPBandsView,
)

urlpatterns = [
    path("symbols/",        SymbolSearchView.as_view(),   name="symbol-search"),
    path("candles/",        CandleView.as_view(),         name="candles"),
    path("pulse/",          MarketPulseView.as_view(),    name="market-pulse"),
    path("rotation/",       SectorRotationView.as_view(), name="sector-rotation"),
    path("shortlist/",      ShortlistView.as_view(),      name="shortlist"),
    path("setup/",          SetupPreviewView.as_view(),   name="setup-preview"),
    path("swing-scanner/",  SwingScannerView.as_view(),   name="swing-scanner"),
    path("ok-backtest/",    OKBacktestView.as_view(),     name="ok-backtest"),
    path("basket/",         BasketView.as_view(),         name="basket-status"),
    path("pyramid/",        PyramidView.as_view(),        name="pyramid"),
    path("liquidity/",      LiquidityMapView.as_view(),   name="liquidity-map"),
    path("orb/",            ORBView.as_view(),            name="orb-tracker"),
    path("vwap-bands/",     VWAPBandsView.as_view(),      name="vwap-bands"),
    path("first-5min/",     First5MinView.as_view(),      name="first-5min"),
    path("orb-failure/",    ORBFailureView.as_view(),     name="orb-failure"),
    path("gap-fill/",       GapFillView.as_view(),        name="gap-fill"),
    path("second-5min/",    Second5MinView.as_view(),     name="second-5min"),
    path("vol-regime/",     VolRegimeView.as_view(),      name="vol-regime"),
    path("sector-rrg/",     SectorRRGView.as_view(),      name="sector-rrg"),
    path("sector-dispersion/", SectorDispersionView.as_view(), name="sector-dispersion"),
    path("tape-speed/",     TapeSpeedView.as_view(),      name="tape-speed"),
    path("news-shocks/",    NewsShockView.as_view(),      name="news-shocks"),
    path("fii-dii-flow/",   FIIDIIFlowView.as_view(),     name="fii-dii-flow"),
    path("depth-imbalance/", DepthImbalanceView.as_view(), name="depth-imbalance"),
]
