# Generated by Django 5.1.15 on 2026-04-18 12:33

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tenant',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('kind', models.CharField(choices=[('retail', 'Retail'), ('advisor', 'Advisor'), ('prop', 'Prop desk')], default='retail', max_length=16)),
                ('slug', models.SlugField(max_length=80, unique=True)),
                ('dedicated', models.BooleanField(default=False, help_text='Route to dedicated DB cluster')),
                ('white_label_domain', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'indexes': [models.Index(fields=['kind'], name='tenants_ten_kind_5b3279_idx')],
            },
        ),
        migrations.CreateModel(
            name='Membership',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('role', models.CharField(choices=[('owner', 'Owner'), ('admin', 'Admin'), ('trader', 'Trader'), ('viewer', 'Viewer'), ('rm', 'Rm'), ('client', 'Client')], default='trader', max_length=16)),
                ('is_active', models.BooleanField(default=True)),
                ('invited_at', models.DateTimeField(auto_now_add=True)),
                ('accepted_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='tenants.tenant')),
            ],
            options={
                'unique_together': {('user', 'tenant')},
            },
        ),
    ]
