# Generated by Django 5.1.15 on 2026-04-18 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Embedding',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('tenant_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('namespace', models.CharField(db_index=True, max_length=64)),
                ('external_id', models.CharField(max_length=128)),
                ('vector', models.JSONField()),
                ('payload', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'indexes': [models.Index(fields=['namespace', 'tenant_id'], name='rag_embeddi_namespa_eb72bf_idx')],
                'unique_together': {('namespace', 'external_id')},
            },
        ),
    ]
