# Generated by Django 5.1.15 on 2026-05-11 06:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rag', '0001_initial'),
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='KnowledgeDoc',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('category', models.CharField(choices=[('ENTRY', 'Entry'), ('EXIT', 'Exit'), ('RISK', 'Risk'), ('SIZING', 'Sizing'), ('FILTER', 'Filter'), ('GENERAL', 'General'), ('RULE', 'Rule'), ('PATTERN', 'Pattern'), ('STRATEGY', 'Strategy')], default='GENERAL', max_length=16)),
                ('is_active', models.BooleanField(default=True)),
                ('legacy_strategy_doc_id', models.IntegerField(blank=True, db_index=True, null=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='tenants.tenant')),
            ],
            options={
                'ordering': ['-updated_at'],
                'indexes': [models.Index(fields=['tenant', 'category', 'is_active'], name='rag_knowled_tenant__882a49_idx')],
            },
        ),
    ]
